---
- name: Configure ToDD Development VM
  hosts: all
  become: true
  become_user: root
  environment:
      GOPATH: /home/vagrant/go
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/go/bin:/usr/local/go/bin/:/home/vagrant/go/src/github.com/toddproject/todd/scripts
  roles:
    - todd
